FROM jenkins/jenkins:lts-jdk21

# Switch to root to install packages
USER root

# Install Docker CLI and add jenkins user to the docker group
RUN apt-get update && apt-get install -y docker.io && usermod -aG docker jenkins

# Switch back to jenkins user
USER jenkins
