version: "3.8"

services:
  mysql:
    image: mysql:9.2
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
