name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu' # Alternative distribution options are available.
            # Remove or comment out both cache steps for a single debug run
            # - name: Cache SonarQube packages
            #   uses: actions/cache@v4
            #   with:
            #     path: ~/.sonar/cache
            #     key: ${{ runner.os }}-sonar
            #     restore-keys: ${{ runner.os }}-sonar
            # - name: Cache Maven packages
            #   uses: actions/cache@v4
            #   with:
            #     path: ~/.m2
            #     key: ${{ runner.os }}-m2-v3-${{ hashFiles('**/pom.xml') }} # Changed key again just in case
          #     restore-keys: ${{ runner.os }}-m2-v3
      - name: Force Clean Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL is generally not needed for SonarQube Cloud as it's implied
          # by sonar.organization and the SonarQube Cloud scanner
        run: mvn -B verify -X -e org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=carlos-ruiz_order-flow-be -Dsonar.organization=carlos-ruiz -Dsonar.projectName='Orders Flow BE'
